from app.routers import (
    auth,
    companies,
    control_plane,
    dashboard,
    enrichment,
    feed,
    dialer,
    health,
    hiring_intent,
    leads,
    outreach,
    opportunity,
    pipeline_ops,
    scheduler,
    scrape,
    telegram,
)

routes = [
    health.router,
    auth.router,
    companies.router,
    leads.router,
    pipeline_ops.router,
    outreach.router,
    dialer.router,
    hiring_intent.router,
    dashboard.router,
    feed.router,
    scrape.router,
    enrichment.router,
    opportunity.router,
    scheduler.router,
    control_plane.router,
    telegram.router,
]
